#!/usr/bin/env bash
# Regenerates the decision index in DESIGN.md, in place, between the markers.
#
# DESIGN.md is 11,600 lines and the entries are not in numeric order, so finding
# D84 means grepping for it. The index is GENERATED rather than typed for the
# reason D34/D111/D128 all record: a hand-kept list of what a file contains is a
# list that goes stale, and this one would go stale on the next decision.
#
#     tools/design_index.sh          # rewrite the block
#     tools/design_index.sh --check  # non-zero if the block is out of date
#
# Cited-but-absent numbers are printed too. A reference to a decision that was
# never written up is worth seeing; silently omitting it reads as "no such
# decision" when what happened is that nobody wrote it.
set -euo pipefail
cd "$(dirname "$0")/.."

DOC=DESIGN.md
BEGIN='<!-- BEGIN GENERATED INDEX -- tools/design_index.sh -->'
END='<!-- END GENERATED INDEX -->'

build() {
	echo "$BEGIN"
	echo
	echo "### The decision log, by number"
	echo
	echo "Generated by \`tools/design_index.sh\` — do not edit between the markers."
	echo "Entries are not in numeric order in the file below; this is the way in."
	echo
	echo '| # | decision |'
	echo '|---|---|'
	# No line numbers, deliberately: the index sits at the top of the file it
	# indexes, so writing them makes the block move the numbers it just wrote.
	# They would also be wrong after any edit. The anchor is the durable handle.
	grep -E '^### D[0-9]+[a-z]? ' "$DOC" \
		| sed -E 's/^### (D[0-9]+[a-z]?) — (.*)$/\1\t\2/' \
		| sort -t$'\t' -k1,1V \
		| while IFS=$'\t' read -r num title; do
			anchor=$(printf '%s — %s' "$num" "$title" \
				| tr '[:upper:]' '[:lower:]' \
				| sed -E 's/[^a-z0-9 -]//g; s/ /-/g')
			printf '| **%s** | [%s](#%s) |\n' "$num" "$title" "$anchor"
		done
	echo

	# D1-D34 live as bullets in chapter 4 rather than as their own sections.
	echo "**D1–D34 are not in that table.** They were settled before the log grew"
	echo "sections and live as bullets under [§4 Design decisions](#4-design-decisions)."
	echo

	local have absent
	have=$(grep -oE '^### D[0-9]+' "$DOC" | sed 's/### D//' | sort -u)
	absent=$(
		for n in $(seq 35 "$(echo "$have" | sort -n | tail -1)"); do
			grep -qx "$n" <<<"$have" || {
				grep -qE "\bD$n\b" "$DOC" && echo -n "D$n "
			}
		done
	)
	if [ -n "$absent" ]; then
		echo "**Cited but never written up:** ${absent% }. Each is referenced by number"
		echo "somewhere in this file and has no entry of its own. D110 is the documented"
		echo "case — D112 records it being left alone while a concurrent session held it."
		echo
	fi
	echo "$END"
}

if [ "${1:-}" = "--check" ]; then
	current=$(awk -v b="$BEGIN" -v e="$END" '$0==b{f=1} f{print} $0==e{f=0}' "$DOC")
	if [ "$current" = "$(build)" ]; then
		echo "design index: current"
	else
		echo "design index: STALE — run tools/design_index.sh" >&2
		exit 1
	fi
	exit 0
fi

if ! grep -qF "$BEGIN" "$DOC"; then
	echo "no index markers in $DOC — add them first" >&2
	exit 1
fi

tmp=$(mktemp)
awk -v b="$BEGIN" -v e="$END" -v f="$(build)" '
	$0==b { print f; skip=1; next }
	$0==e { skip=0; next }
	!skip { print }
' "$DOC" >"$tmp"
mv "$tmp" "$DOC"
echo "design index: rewritten ($(grep -cE '^\| \*\*D' "$DOC") entries)"
